version: '3.3' 
services:
  web: 
    image: nawinnc/gitea:0555
    networks: 
    - webproxy 
    logging:
      driver: json-file
    container_name: giteaapp
    deploy: 
      replicas: 1 
      labels: 
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.spcn15gitea-https.entrypoints=websecure 
        - traefik.http.routers.spcn15gitea-https.rule=Host("spcn15gitea.xops.ipv9.xyz")
        - traefik.http.routers.spcn15gitea-https.tls.certresolver=default
        - traefik.http.services.spcn15gitea.loadbalancer.server.port=3000 
      resources: 
        reservations: 
          cpus: '0.1'
          memory: 10M
        limits: 
          cpus: '0.4'
          memory: 150M
networks: 
  webproxy: 
    external: true
